CREATE TYPE "ai_conversation_surface" AS ENUM('telegram_bot', 'web', 'api');--> statement-breakpoint
CREATE TYPE "ai_conversation_status" AS ENUM('active', 'archived');--> statement-breakpoint
CREATE TYPE "ai_message_role" AS ENUM('system', 'user', 'assistant', 'tool');--> statement-breakpoint
CREATE TABLE "ai_conversations" (
	"id" SERIAL PRIMARY KEY,
	"surface" "ai_conversation_surface" NOT NULL,
	"external_chat_id" TEXT NOT NULL,
	"external_thread_id" TEXT,
	"status" "ai_conversation_status" DEFAULT 'active' NOT NULL,
	"title" TEXT,
	"last_message_at" TIMESTAMP WITH TIME ZONE,
	"created_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	"updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE "ai_messages" (
	"id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"conversation_id" INTEGER NOT NULL,
	"role" "ai_message_role" NOT NULL,
	"content" TEXT NOT NULL,
	"model_name" TEXT,
	"input_tokens" INTEGER,
	"output_tokens" INTEGER,
	"tool_name" TEXT,
	"tool_call_id" TEXT,
	"metadata" JSONB,
	"created_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE UNIQUE INDEX "ai_conversations_surface_thread_uq" ON "ai_conversations" USING btree ("surface","external_chat_id","external_thread_id");--> statement-breakpoint
CREATE INDEX "ai_conversations_status_idx" ON "ai_conversations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ai_conversations_last_message_at_idx" ON "ai_conversations" USING btree ("last_message_at");--> statement-breakpoint
CREATE INDEX "ai_messages_conversation_created_idx" ON "ai_messages" USING btree ("conversation_id","created_at");--> statement-breakpoint
ALTER TABLE "ai_messages" ADD CONSTRAINT "ai_messages_conversation_id_ai_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations"("id") ON DELETE cascade ON UPDATE no action;
